export const PERMISSIONS = {
  OPEN_REGISTER: "open_register",
  PROCESS_SALE: "process_sale",
  APPLY_DISCOUNT: "apply_discount",
  PROCESS_REFUND: "process_refund",
  VOID_ORDER: "void_order",
  VIEW_PRODUCTS: "view_products",
  MANAGE_PRODUCTS: "manage_products",
  VIEW_INVENTORY: "view_inventory",
  MANAGE_INVENTORY: "manage_inventory",
  ADJUST_INVENTORY: "adjust_inventory",
  RECEIVE_INVENTORY: "receive_inventory",
  PERFORM_INVENTORY_COUNT: "perform_inventory_count",
  MANAGE_CUSTOMERS: "manage_customers",
  VIEW_REPORTS: "view_reports",
  MANAGE_EMPLOYEES: "manage_employees",
  MANAGE_STRIPE: "manage_stripe",
  MANAGE_LOCATIONS: "manage_locations",
  VIEW_WORKFORCE: "view_workforce",
  MANAGE_WORKFORCE: "manage_workforce",
  VIEW_EMPLOYEE_PERSONAL: "view_employee_personal",
  VIEW_COMPENSATION: "view_compensation",
  MANAGE_COMPENSATION: "manage_compensation",
  VIEW_PAYROLL: "view_payroll",
  MANAGE_PAYROLL: "manage_payroll",
  MANAGE_TIME_ENTRIES: "manage_time_entries",
  APPROVE_TIME_OFF: "approve_time_off",
  REVIEW_TIME_OFF: "review_time_off",
  MANAGE_WORKFORCE_SETTINGS: "manage_workforce_settings",
  REQUEST_TIME_OFF: "request_time_off",
  // Expense management
  CREATE_EXPENSE: "create_expense",
  VIEW_OWN_EXPENSES: "view_own_expenses",
  VIEW_TEAM_EXPENSES: "view_team_expenses",
  APPROVE_EXPENSES: "approve_expenses",
  MANAGE_EXPENSE_CARDS: "manage_expense_cards",
  MANAGE_EXPENSE_CATEGORIES: "manage_expense_categories",
  VIEW_EXPENSE_REPORTS: "view_expense_reports",
  EXPORT_EXPENSES: "export_expenses",
  MANAGE_EXPENSE_BUDGETS: "manage_expense_budgets",
  MANAGE_EXPENSE_SETTINGS: "manage_expense_settings",
  REIMBURSE_EXPENSES: "reimburse_expenses",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const WORKFORCE_VIEW: PermissionKey[] = [
  PERMISSIONS.VIEW_WORKFORCE,
  PERMISSIONS.REQUEST_TIME_OFF,
];

const WORKFORCE_MANAGE: PermissionKey[] = [
  PERMISSIONS.MANAGE_WORKFORCE,
  PERMISSIONS.MANAGE_TIME_ENTRIES,
  PERMISSIONS.MANAGE_WORKFORCE_SETTINGS,
];

const WORKFORCE_HR: PermissionKey[] = [
  PERMISSIONS.VIEW_EMPLOYEE_PERSONAL,
  PERMISSIONS.MANAGE_EMPLOYEES,
  PERMISSIONS.VIEW_COMPENSATION,
  PERMISSIONS.MANAGE_COMPENSATION,
];

const WORKFORCE_PAYROLL: PermissionKey[] = [
  PERMISSIONS.VIEW_PAYROLL,
  PERMISSIONS.MANAGE_PAYROLL,
  PERMISSIONS.REVIEW_TIME_OFF,
  PERMISSIONS.APPROVE_TIME_OFF,
];

const INVENTORY_OPS: PermissionKey[] = [
  PERMISSIONS.VIEW_INVENTORY,
  PERMISSIONS.MANAGE_INVENTORY,
  PERMISSIONS.ADJUST_INVENTORY,
  PERMISSIONS.RECEIVE_INVENTORY,
  PERMISSIONS.PERFORM_INVENTORY_COUNT,
];

const PRODUCT_OPS: PermissionKey[] = [
  PERMISSIONS.VIEW_PRODUCTS,
  PERMISSIONS.MANAGE_PRODUCTS,
];

const EXPENSE_EMPLOYEE: PermissionKey[] = [
  PERMISSIONS.CREATE_EXPENSE,
  PERMISSIONS.VIEW_OWN_EXPENSES,
];

const EXPENSE_MANAGER: PermissionKey[] = [
  ...EXPENSE_EMPLOYEE,
  PERMISSIONS.VIEW_TEAM_EXPENSES,
  PERMISSIONS.APPROVE_EXPENSES,
  PERMISSIONS.VIEW_EXPENSE_REPORTS,
];

const EXPENSE_FINANCE: PermissionKey[] = [
  ...EXPENSE_MANAGER,
  PERMISSIONS.MANAGE_EXPENSE_CARDS,
  PERMISSIONS.MANAGE_EXPENSE_CATEGORIES,
  PERMISSIONS.EXPORT_EXPENSES,
  PERMISSIONS.MANAGE_EXPENSE_BUDGETS,
  PERMISSIONS.MANAGE_EXPENSE_SETTINGS,
  PERMISSIONS.REIMBURSE_EXPENSES,
];

export const ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  Owner: Object.values(PERMISSIONS),
  Admin: [
    PERMISSIONS.OPEN_REGISTER,
    PERMISSIONS.PROCESS_SALE,
    PERMISSIONS.APPLY_DISCOUNT,
    PERMISSIONS.PROCESS_REFUND,
    PERMISSIONS.VOID_ORDER,
    ...PRODUCT_OPS,
    ...INVENTORY_OPS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_EMPLOYEES,
    PERMISSIONS.MANAGE_STRIPE,
    PERMISSIONS.MANAGE_LOCATIONS,
    ...WORKFORCE_VIEW,
    ...WORKFORCE_MANAGE,
    ...WORKFORCE_HR,
    ...WORKFORCE_PAYROLL,
    PERMISSIONS.REQUEST_TIME_OFF,
    ...EXPENSE_FINANCE,
  ],
  Manager: [
    PERMISSIONS.OPEN_REGISTER,
    PERMISSIONS.PROCESS_SALE,
    PERMISSIONS.APPLY_DISCOUNT,
    PERMISSIONS.PROCESS_REFUND,
    ...PRODUCT_OPS,
    ...INVENTORY_OPS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_LOCATIONS,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.MANAGE_WORKFORCE,
    PERMISSIONS.MANAGE_TIME_ENTRIES,
    PERMISSIONS.VIEW_EMPLOYEE_PERSONAL,
    PERMISSIONS.VIEW_COMPENSATION,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.REVIEW_TIME_OFF,
    PERMISSIONS.APPROVE_TIME_OFF,
    PERMISSIONS.REQUEST_TIME_OFF,
    ...EXPENSE_MANAGER,
  ],
  Cashier: [
    PERMISSIONS.OPEN_REGISTER,
    PERMISSIONS.PROCESS_SALE,
    PERMISSIONS.APPLY_DISCOUNT,
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.REQUEST_TIME_OFF,
    ...EXPENSE_EMPLOYEE,
  ],
  "Inventory Staff": [
    ...PRODUCT_OPS,
    ...INVENTORY_OPS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.REQUEST_TIME_OFF,
    ...EXPENSE_EMPLOYEE,
  ],
  "Reports Viewer": [
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.REQUEST_TIME_OFF,
    PERMISSIONS.VIEW_OWN_EXPENSES,
    PERMISSIONS.VIEW_EXPENSE_REPORTS,
  ],
  Finance: [
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_PAYROLL,
    ...EXPENSE_FINANCE,
  ],
};

/** @deprecated Use APPROVE_TIME_OFF or REVIEW_TIME_OFF */
export function isTimeOffReviewer(permissions: PermissionKey[]): boolean {
  return (
    permissions.includes(PERMISSIONS.APPROVE_TIME_OFF) ||
    permissions.includes(PERMISSIONS.REVIEW_TIME_OFF)
  );
}
