export const PERMISSIONS = {
  OPEN_REGISTER: "open_register",
  PROCESS_SALE: "process_sale",
  APPLY_DISCOUNT: "apply_discount",
  PROCESS_REFUND: "process_refund",
  VOID_ORDER: "void_order",
  MANAGE_PRODUCTS: "manage_products",
  MANAGE_INVENTORY: "manage_inventory",
  MANAGE_CUSTOMERS: "manage_customers",
  VIEW_REPORTS: "view_reports",
  MANAGE_EMPLOYEES: "manage_employees",
  MANAGE_BILLING: "manage_billing",
  MANAGE_STRIPE: "manage_stripe",
  MANAGE_LOCATIONS: "manage_locations",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  Owner: Object.values(PERMISSIONS),
  Admin: [
    PERMISSIONS.OPEN_REGISTER,
    PERMISSIONS.PROCESS_SALE,
    PERMISSIONS.APPLY_DISCOUNT,
    PERMISSIONS.PROCESS_REFUND,
    PERMISSIONS.VOID_ORDER,
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_EMPLOYEES,
    PERMISSIONS.MANAGE_STRIPE,
    PERMISSIONS.MANAGE_LOCATIONS,
  ],
  Manager: [
    PERMISSIONS.OPEN_REGISTER,
    PERMISSIONS.PROCESS_SALE,
    PERMISSIONS.APPLY_DISCOUNT,
    PERMISSIONS.PROCESS_REFUND,
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_LOCATIONS,
  ],
  Cashier: [
    PERMISSIONS.OPEN_REGISTER,
    PERMISSIONS.PROCESS_SALE,
    PERMISSIONS.APPLY_DISCOUNT,
    PERMISSIONS.MANAGE_CUSTOMERS,
  ],
  "Inventory Staff": [
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_REPORTS,
  ],
  "Reports Viewer": [PERMISSIONS.VIEW_REPORTS],
};
