"use client";

import { ChangeEvent, useMemo, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Archive, Calculator, Download, ImageDown, QrCode, Ruler, ScanBarcode } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { OfficeSuiteModule } from "@/lib/office/suite";
import { convertUnit, unitsFor, type UnitKind } from "@/lib/office/converters";
import { OfficeAppHeader } from "./app-header";

type Tool = "calculator" | "converter" | "qr" | "image" | "zip";
const toolList = [
  { id: "calculator" as const, name: "Calculator", icon: Calculator, detail: "Totals, tax, discount, margin" },
  { id: "converter" as const, name: "Unit converter", icon: Ruler, detail: "Length, weight, temperature" },
  { id: "qr" as const, name: "QR code", icon: QrCode, detail: "Generate and download PNG" },
  { id: "image" as const, name: "Resize image", icon: ImageDown, detail: "Resize and compress locally" },
  { id: "zip" as const, name: "Create ZIP", icon: Archive, detail: "Package selected files" },
];

export function UtilitiesApp({ module }: { module: OfficeSuiteModule }) {
  const [tool, setTool] = useState<Tool>("calculator");
  const [amount, setAmount] = useState(100); const [percent, setPercent] = useState(8.25); const [operation, setOperation] = useState<"add" | "subtract" | "percent" | "margin">("add");
  const calculation = operation === "add" ? amount + amount * percent / 100 : operation === "subtract" ? amount - amount * percent / 100 : operation === "percent" ? amount * percent / 100 : amount ? (amount - percent) / amount * 100 : 0;
  const [kind, setKind] = useState<UnitKind>("length"); const units = unitsFor(kind); const [from, setFrom] = useState("meters"); const [to, setTo] = useState("feet"); const [unitValue, setUnitValue] = useState(1);
  const converted = useMemo(() => convertUnit(unitValue, kind, units.includes(from) ? from : units[0], units.includes(to) ? to : units[1]), [unitValue, kind, from, to, units]);
  const [qrText, setQrText] = useState(""); const [qrUrl, setQrUrl] = useState(""); const [working, setWorking] = useState(false);
  const [imageFile, setImageFile] = useState<File | null>(null); const [width, setWidth] = useState(1200); const [quality, setQuality] = useState(82);
  const [zipFiles, setZipFiles] = useState<File[]>([]);
  async function makeQr() { if (!qrText.trim()) return toast.error("Enter text or a URL"); setWorking(true); try { const QRCodeModule = await import("qrcode"); setQrUrl(await QRCodeModule.toDataURL(qrText, { width: 900, margin: 2, errorCorrectionLevel: "M" })); } catch { toast.error("Could not generate QR code"); } finally { setWorking(false); } }
  async function resizeImage() { if (!imageFile) return toast.error("Choose an image first"); setWorking(true); try { const image = document.createElement("img"); const url = URL.createObjectURL(imageFile); await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("Invalid image")); image.src = url; }); const targetWidth = Math.max(1, width); const targetHeight = Math.round(image.height * targetWidth / image.width); const canvas = document.createElement("canvas"); canvas.width = targetWidth; canvas.height = targetHeight; canvas.getContext("2d")!.drawImage(image, 0, 0, targetWidth, targetHeight); URL.revokeObjectURL(url); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", quality / 100)); if (!blob) throw new Error("Resize failed"); const output = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = output; link.download = `${imageFile.name.replace(/\.[^.]+$/, "")}-${targetWidth}px.jpg`; link.click(); URL.revokeObjectURL(output); toast.success(`Resized to ${targetWidth} × ${targetHeight}`); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not resize image"); } finally { setWorking(false); } }
  async function createZip() { if (!zipFiles.length) return toast.error("Choose at least one file"); setWorking(true); try { const { default: JSZip } = await import("jszip"); const zip = new JSZip(); zipFiles.forEach((file) => zip.file(file.name, file)); const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "business-files.zip"; link.click(); URL.revokeObjectURL(url); toast.success("ZIP file created"); } catch { toast.error("Could not create ZIP file"); } finally { setWorking(false); } }
  function chooseFiles(event: ChangeEvent<HTMLInputElement>) { setZipFiles(Array.from(event.target.files ?? [])); }
  return <div className="space-y-5 pb-8"><OfficeAppHeader module={module}><Button asChild variant="outline"><Link href="/register"><ScanBarcode className="h-4 w-4" />Open register scanner</Link></Button></OfficeAppHeader>
    <div className="grid gap-4 lg:grid-cols-[300px_1fr]">
      <nav className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm" aria-label="Utility tools">{toolList.map(({ id, name, detail, icon: Icon }) => <button key={id} onClick={() => setTool(id)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left transition ${tool === id ? "bg-zinc-900 text-white" : "hover:bg-zinc-100"}`}><div className={`rounded-lg p-2 ${tool === id ? "bg-white/10" : "bg-zinc-100"}`}><Icon className="h-5 w-5" /></div><div><span className="block text-sm font-semibold">{name}</span><span className={`block text-xs ${tool === id ? "text-zinc-300" : "text-zinc-500"}`}>{detail}</span></div></button>)}</nav>
      <main className="min-h-[560px] rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8">
        {tool === "calculator" ? <div className="mx-auto max-w-2xl"><div className="rounded-2xl bg-zinc-950 p-6 text-white"><p className="text-sm text-zinc-400">Result</p><p className="mt-2 break-all text-5xl font-semibold tabular-nums">{Number.isFinite(calculation) ? calculation.toLocaleString(undefined, { maximumFractionDigits: 4 }) : "—"}</p></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">{operation === "margin" ? "Revenue" : "Base amount"}<Input type="number" value={amount} onChange={(e) => setAmount(Number(e.target.value))} className="mt-1" /></label><label className="text-sm font-medium">{operation === "margin" ? "Cost" : "Percentage"}<Input type="number" value={percent} onChange={(e) => setPercent(Number(e.target.value))} className="mt-1" /></label></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{([{ id: "add", label: "Add %" }, { id: "subtract", label: "Discount %" }, { id: "percent", label: "% of amount" }, { id: "margin", label: "Margin %" }] as const).map((item) => <button key={item.id} onClick={() => setOperation(item.id)} className={`rounded-xl border px-3 py-3 text-sm font-semibold ${operation === item.id ? "border-zinc-900 bg-zinc-900 text-white" : "border-zinc-200"}`}>{item.label}</button>)}</div></div> : null}
        {tool === "converter" ? <div className="mx-auto max-w-2xl"><h2 className="text-2xl font-semibold">Unit converter</h2><div className="mt-5 grid grid-cols-3 rounded-xl bg-zinc-100 p-1">{(["length", "weight", "temperature"] as const).map((item) => <button key={item} onClick={() => { setKind(item); const next = unitsFor(item); setFrom(next[0]); setTo(next[1]); }} className={`rounded-lg px-3 py-2 text-sm capitalize ${kind === item ? "bg-white shadow-sm" : "text-zinc-500"}`}>{item}</button>)}</div><div className="mt-8 grid items-end gap-4 sm:grid-cols-[1fr_auto_1fr]"><label className="text-sm font-medium">From<Input type="number" value={unitValue} onChange={(e) => setUnitValue(Number(e.target.value))} className="mt-1" /><select value={from} onChange={(e) => setFrom(e.target.value)} className="mt-2 h-10 w-full rounded-md border px-3 capitalize">{units.map((unit) => <option key={unit}>{unit}</option>)}</select></label><span className="pb-3 text-2xl text-zinc-300">=</span><label className="text-sm font-medium">To<div className="mt-1 flex h-10 items-center rounded-md border bg-zinc-50 px-3 font-semibold">{converted.toLocaleString(undefined, { maximumFractionDigits: 6 })}</div><select value={to} onChange={(e) => setTo(e.target.value)} className="mt-2 h-10 w-full rounded-md border px-3 capitalize">{units.map((unit) => <option key={unit}>{unit}</option>)}</select></label></div></div> : null}
        {tool === "qr" ? <div className="mx-auto grid max-w-3xl gap-8 md:grid-cols-2"><div><h2 className="text-2xl font-semibold">QR code generator</h2><p className="mt-2 text-sm text-zinc-500">Create a scannable code for a website, Wi-Fi note, contact detail, or plain text.</p><label className="mt-6 block text-sm font-medium">Text or URL<Input value={qrText} onChange={(e) => setQrText(e.target.value)} className="mt-1" placeholder="https://yourbusiness.com" /></label><Button className="mt-4" onClick={makeQr} disabled={working}><QrCode className="h-4 w-4" />Generate QR code</Button></div><div className="flex aspect-square items-center justify-center rounded-2xl border border-dashed bg-zinc-50 p-6">{qrUrl ? <div className="text-center"><Image src={qrUrl} alt="Generated QR code" width={256} height={256} unoptimized className="mx-auto w-full max-w-64" /><a href={qrUrl} download="qr-code.png" className="mt-3 inline-flex items-center text-sm font-semibold"><Download className="mr-1 h-4 w-4" />Download PNG</a></div> : <p className="text-center text-sm text-zinc-400">Your QR code will appear here.</p>}</div></div> : null}
        {tool === "image" ? <div className="mx-auto max-w-2xl"><h2 className="text-2xl font-semibold">Resize and compress image</h2><p className="mt-2 text-sm text-zinc-500">Processing happens in your browser; the selected image is not uploaded.</p><label className="mt-6 block rounded-2xl border-2 border-dashed p-8 text-center"><ImageDown className="mx-auto h-8 w-8 text-zinc-300" /><span className="mt-2 block text-sm font-medium">{imageFile?.name ?? "Choose JPG, PNG, or WebP"}</span><input type="file" accept="image/jpeg,image/png,image/webp" className="mt-3 text-sm" onChange={(e) => setImageFile(e.target.files?.[0] ?? null)} /></label><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Output width (pixels)<Input type="number" min="1" max="10000" value={width} onChange={(e) => setWidth(Number(e.target.value))} className="mt-1" /></label><label className="text-sm font-medium">JPEG quality: {quality}%<input type="range" min="20" max="100" value={quality} onChange={(e) => setQuality(Number(e.target.value))} className="mt-3 w-full" /></label></div><Button className="mt-5" onClick={resizeImage} disabled={working || !imageFile}><Download className="h-4 w-4" />Resize & download</Button></div> : null}
        {tool === "zip" ? <div className="mx-auto max-w-2xl"><h2 className="text-2xl font-semibold">Create a ZIP file</h2><p className="mt-2 text-sm text-zinc-500">Package multiple files into one downloadable archive. Files stay in your browser.</p><label className="mt-6 block rounded-2xl border-2 border-dashed p-8 text-center"><Archive className="mx-auto h-8 w-8 text-zinc-300" /><span className="mt-2 block text-sm font-medium">{zipFiles.length ? `${zipFiles.length} file${zipFiles.length === 1 ? "" : "s"} selected` : "Choose files to package"}</span><input type="file" multiple className="mt-3 text-sm" onChange={chooseFiles} /></label>{zipFiles.length ? <ul className="mt-4 max-h-40 overflow-auto rounded-xl bg-zinc-50 p-3 text-sm">{zipFiles.map((file) => <li key={`${file.name}-${file.size}`} className="flex justify-between py-1"><span className="truncate">{file.name}</span><span className="ml-3 text-zinc-400">{(file.size / 1024).toFixed(1)} KB</span></li>)}</ul> : null}<Button className="mt-5" onClick={createZip} disabled={working || !zipFiles.length}><Download className="h-4 w-4" />Create & download ZIP</Button></div> : null}
      </main>
    </div>
  </div>;
}
