"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowRight, FileText, FolderKanban, History, Play, Plus, Save, ShieldCheck, Workflow } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { OfficeSuiteModule } from "@/lib/office/suite";
import type { OfficeWorkspaceRecordSummary } from "@/lib/office/workspace-service";
import { OfficeAppHeader } from "./app-header";
import { createWorkspaceRecord, recordMetadata, updateWorkspaceRecord, type OfficeAppPermissions } from "./record-client";

type Run = { at: string; outputId: string; workspace: string };
type WorkflowData = { kind: "workflow"; action: "CREATE_PROJECT" | "CREATE_DRAFT"; outputTitle: string; outputSummary: string; runs: Run[] };
const blank: WorkflowData = { kind: "workflow", action: "CREATE_PROJECT", outputTitle: "", outputSummary: "", runs: [] };

export function WorkflowsApp({ module, initialRecords, permissions }: { module: OfficeSuiteModule; initialRecords: OfficeWorkspaceRecordSummary[]; permissions: OfficeAppPermissions }) {
  const [records, setRecords] = useState(initialRecords);
  const [activeId, setActiveId] = useState(initialRecords[0]?.id ?? "");
  const active = records.find((record) => record.id === activeId);
  const [name, setName] = useState(active?.title ?? "New workflow");
  const [data, setData] = useState<WorkflowData>(recordMetadata(active, blank));
  const [confirming, setConfirming] = useState(false);
  const [busy, setBusy] = useState(false);
  function load(record?: OfficeWorkspaceRecordSummary) { setActiveId(record?.id ?? ""); setName(record?.title ?? "New workflow"); setData(recordMetadata(record, blank)); }
  async function save() { if (!name.trim() || !data.outputTitle.trim()) { toast.error("Name the workflow and its output"); return undefined; } setBusy(true); try { const saved = active ? await updateWorkspaceRecord(module.slug, active.id, { title: name, summary: `Manual: ${data.action === "CREATE_PROJECT" ? "create project" : "create email draft"}`, metadata: data }) : await createWorkspaceRecord(module.slug, { title: name, summary: `Manual: ${data.action === "CREATE_PROJECT" ? "create project" : "create email draft"}`, metadata: data }); setRecords((items) => active ? items.map((item) => item.id === saved.id ? saved : item) : [saved, ...items]); setActiveId(saved.id); toast.success("Workflow saved"); return saved; } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save workflow"); } finally { setBusy(false); } }
  async function run(event: FormEvent) { event.preventDefault(); setBusy(true); try { let record = active; if (!record) record = await save(); if (!record) return; const response = await fetch("/api/office/workflows/run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recordId: record.id, confirmed: true }) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? "Could not run workflow"); const run: Run = { at: new Date().toISOString(), outputId: body.output.id, workspace: body.workspace }; const next = { ...data, runs: [run, ...data.runs] }; setData(next); const updated = { ...record, metadata: next, updatedAt: new Date().toISOString() }; setRecords((items) => items.map((item) => item.id === updated.id ? updated : item)); setConfirming(false); toast.success(body.workspace === "projects" ? "Project created" : "Email draft created"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not run workflow"); } finally { setBusy(false); } }
  return <div className="space-y-5 pb-8"><OfficeAppHeader module={module}><Button variant="outline" onClick={() => load()} disabled={!permissions.canCreate}><Plus className="h-4 w-4" />New workflow</Button><Button onClick={save} disabled={busy}><Save className="h-4 w-4" />Save</Button></OfficeAppHeader>
    <div className="grid gap-4 xl:grid-cols-[280px_1fr_320px]">
      <aside className="rounded-2xl border border-purple-200 bg-purple-950 p-4 text-white"><div className="flex items-center gap-2"><Workflow className="h-5 w-5 text-purple-300" /><h2 className="font-semibold">Saved workflows</h2></div><div className="mt-4 space-y-2">{records.map((record) => <button key={record.id} onClick={() => load(record)} className={`w-full rounded-xl p-3 text-left ${record.id === activeId ? "bg-purple-400 text-purple-950" : "bg-white/5 hover:bg-white/10"}`}><span className="block truncate text-sm font-semibold">{record.title}</span><span className="mt-1 block text-xs opacity-70">{record.summary}</span></button>)}{!records.length ? <p className="rounded-xl bg-white/5 p-4 text-sm text-purple-200">No workflows yet.</p> : null}</div></aside>
      <main className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-xs font-semibold uppercase tracking-wider text-purple-700">Workflow builder</p><Input value={name} onChange={(e) => setName(e.target.value)} className="mt-2 border-0 px-0 text-2xl font-semibold shadow-none focus-visible:ring-0" aria-label="Workflow name" /><div className="mt-7 flex items-center gap-3"><div className="flex-1 rounded-xl border-2 border-purple-200 bg-purple-50 p-4"><span className="text-[11px] font-semibold uppercase tracking-wider text-purple-600">Trigger</span><p className="mt-1 font-semibold">Run manually</p><p className="mt-1 text-xs text-slate-500">A person reviews and confirms every run.</p></div><ArrowRight className="h-5 w-5 shrink-0 text-purple-300" /><div className="flex-1 rounded-xl border-2 border-slate-200 p-4"><span className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">Action</span><select value={data.action} onChange={(e) => setData((current) => ({ ...current, action: e.target.value as WorkflowData["action"] }))} className="mt-1 h-9 w-full rounded-md border bg-white px-2 text-sm font-semibold"><option value="CREATE_PROJECT">Create a project</option><option value="CREATE_DRAFT">Create an email draft</option></select></div></div><div className="mt-6 grid gap-4"><label className="text-sm font-medium">Output title<Input value={data.outputTitle} onChange={(e) => setData((current) => ({ ...current, outputTitle: e.target.value }))} className="mt-1" placeholder={data.action === "CREATE_PROJECT" ? "Monthly close" : "Customer follow-up"} /></label><label className="text-sm font-medium">Starting details<Textarea value={data.outputSummary} onChange={(e) => setData((current) => ({ ...current, outputSummary: e.target.value }))} className="mt-1 min-h-32" /></label></div><div className="mt-6 flex items-center justify-between gap-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 text-emerald-700" /><div><p className="text-sm font-semibold text-emerald-900">No background surprises</p><p className="text-xs text-emerald-700">This runs only when you confirm it.</p></div></div><Button onClick={() => { if (!data.outputTitle.trim()) toast.error("Add an output title"); else setConfirming(true); }}><Play className="h-4 w-4" />Review run</Button></div></main>
      <aside className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><History className="h-5 w-5 text-slate-400" /><h2 className="font-semibold">Run history</h2></div><div className="mt-4 space-y-3">{data.runs.map((run) => <div key={`${run.outputId}-${run.at}`} className="rounded-xl bg-slate-50 p-3"><div className="flex gap-2">{run.workspace === "projects" ? <FolderKanban className="h-4 w-4 text-amber-600" /> : <FileText className="h-4 w-4 text-violet-600" />}<div><p className="text-sm font-medium">{run.workspace === "projects" ? "Project created" : "Email draft created"}</p><p className="mt-1 text-xs text-slate-500">{new Date(run.at).toLocaleString()}</p></div></div><Link href={`/office/apps/${run.workspace === "projects" ? "projects" : "communication"}`} className="mt-2 inline-flex text-xs font-semibold text-purple-700">Open output →</Link></div>)}{!data.runs.length ? <p className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-500">Confirmed runs appear here.</p> : null}</div></aside>
    </div>
    <Dialog open={confirming} onOpenChange={setConfirming}><DialogContent><form onSubmit={run}><DialogHeader><DialogTitle>Run “{name}”?</DialogTitle><DialogDescription>This will create one new {data.action === "CREATE_PROJECT" ? "project" : "email draft"}. It will not send a message or charge money.</DialogDescription></DialogHeader><div className="my-5 rounded-xl bg-slate-50 p-4"><p className="font-semibold">{data.outputTitle}</p><p className="mt-1 text-sm text-slate-600">{data.outputSummary}</p></div><DialogFooter><Button type="button" variant="outline" onClick={() => setConfirming(false)}>Cancel</Button><Button type="submit" disabled={busy}><Play className="h-4 w-4" />{busy ? "Running…" : "Confirm run"}</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}
