import {
  Bot,
  Calculator,
  CalendarDays,
  FileSpreadsheet,
  Files,
  FileSignature,
  FileText,
  FolderKanban,
  Landmark,
  LibraryBig,
  Mail,
  Presentation,
  ScanText,
  ShieldCheck,
  Users,
  UsersRound,
  type LucideIcon,
} from "lucide-react";
import type { OfficeSuiteIcon } from "@/lib/office/suite";

export const OFFICE_SUITE_ICONS: Record<OfficeSuiteIcon, LucideIcon> = {
  files: Files,
  document: FileText,
  sheet: FileSpreadsheet,
  presentation: Presentation,
  pdf: ScanText,
  message: Mail,
  calendar: CalendarDays,
  customers: UsersRound,
  forms: FileSignature,
  finance: Landmark,
  projects: FolderKanban,
  people: Users,
  knowledge: LibraryBig,
  security: ShieldCheck,
  automation: Bot,
  utilities: Calculator,
};
export const OFFICE_ACCENTS: Record<string, { icon: string; soft: string; border: string; text: string }> = {
  sky: { icon: "bg-sky-600", soft: "bg-sky-50", border: "border-sky-200", text: "text-sky-700" },
  blue: { icon: "bg-blue-600", soft: "bg-blue-50", border: "border-blue-200", text: "text-blue-700" },
  emerald: { icon: "bg-emerald-600", soft: "bg-emerald-50", border: "border-emerald-200", text: "text-emerald-700" },
  orange: { icon: "bg-orange-600", soft: "bg-orange-50", border: "border-orange-200", text: "text-orange-700" },
  rose: { icon: "bg-rose-600", soft: "bg-rose-50", border: "border-rose-200", text: "text-rose-700" },
  violet: { icon: "bg-violet-600", soft: "bg-violet-50", border: "border-violet-200", text: "text-violet-700" },
  indigo: { icon: "bg-indigo-600", soft: "bg-indigo-50", border: "border-indigo-200", text: "text-indigo-700" },
  cyan: { icon: "bg-cyan-600", soft: "bg-cyan-50", border: "border-cyan-200", text: "text-cyan-700" },
  fuchsia: { icon: "bg-fuchsia-600", soft: "bg-fuchsia-50", border: "border-fuchsia-200", text: "text-fuchsia-700" },
  amber: { icon: "bg-amber-600", soft: "bg-amber-50", border: "border-amber-200", text: "text-amber-700" },
  teal: { icon: "bg-teal-600", soft: "bg-teal-50", border: "border-teal-200", text: "text-teal-700" },
  lime: { icon: "bg-lime-600", soft: "bg-lime-50", border: "border-lime-200", text: "text-lime-700" },
  slate: { icon: "bg-slate-700", soft: "bg-slate-100", border: "border-slate-200", text: "text-slate-700" },
  purple: { icon: "bg-purple-600", soft: "bg-purple-50", border: "border-purple-200", text: "text-purple-700" },
  zinc: { icon: "bg-zinc-700", soft: "bg-zinc-100", border: "border-zinc-200", text: "text-zinc-700" },
};
