"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, FilePlus2, Search, Star, X } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { OFFICE_SUITE_GROUPS, OFFICE_SUITE_MODULES, officeModuleHref, type OfficeSuiteGroup } from "@/lib/office/suite";
import type { OfficeWorkspaceRecordSummary } from "@/lib/office/workspace-service";
import { OFFICE_ACCENTS, OFFICE_SUITE_ICONS } from "./office-suite-icons";

type OfficeMetrics = { documents: number; customers: number | null; employees: number | null; openOrders: number | null; openWork: number; pendingExpenses: number | null };
type Props = { businessName: string; firstName: string; metrics: OfficeMetrics; recentRecords: OfficeWorkspaceRecordSummary[]; canCreate: boolean };
const FAVORITES_KEY = "nexapos-office-favorites-v2";

export function OfficeCommandCenter({ businessName, firstName, metrics, recentRecords, canCreate }: Props) {
  const [query, setQuery] = useState("");
  const [group, setGroup] = useState<OfficeSuiteGroup | "All">("All");
  const [favorites, setFavorites] = useState<string[]>([]);
  useEffect(() => { try { setFavorites(JSON.parse(localStorage.getItem(FAVORITES_KEY) ?? "[]")); } catch {} }, []);
  const visible = useMemo(() => OFFICE_SUITE_MODULES.filter((module) => {
    if (group !== "All" && module.group !== group) return false;
    const term = query.trim().toLowerCase();
    return !term || `${module.name} ${module.description} ${module.features.join(" ")} ${module.quickActions.map((item) => item.label).join(" ")}`.toLowerCase().includes(term);
  }).sort((a, b) => Number(favorites.includes(b.slug)) - Number(favorites.includes(a.slug))), [query, group, favorites]);
  function favorite(slug: string) { setFavorites((items) => { const next = items.includes(slug) ? items.filter((item) => item !== slug) : [...items, slug]; try { localStorage.setItem(FAVORITES_KEY, JSON.stringify(next)); } catch {} return next; }); }
  const priorityActions = [
    { label: "Write a document", href: "/office/new", detail: "Editor and templates", icon: "document" as const, tone: "bg-blue-600" },
    { label: "Build a spreadsheet", href: "/office/apps/spreadsheets", detail: "Formulas and CSV", icon: "sheet" as const, tone: "bg-emerald-600" },
    { label: "Book an appointment", href: "/office/apps/calendar", detail: "Conflict-checked", icon: "calendar" as const, tone: "bg-indigo-600" },
    { label: "Scan paperwork", href: "/office/scan", detail: "Capture and organize", icon: "pdf" as const, tone: "bg-rose-600" },
  ];
  return <div className="space-y-7 pb-8">
    <section className="relative overflow-hidden rounded-[1.75rem] bg-slate-950 px-5 py-7 text-white shadow-xl sm:px-8 sm:py-9">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_85%_15%,rgba(99,102,241,.26),transparent_28%),radial-gradient(circle_at_5%_100%,rgba(16,185,129,.16),transparent_30%)]" />
      <div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><Badge className="border-white/10 bg-white/10 text-white hover:bg-white/10">Office & Admin · {businessName}</Badge><h1 className="mt-5 max-w-3xl text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Good day, {firstName}. Choose the job—not the software.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">Every item below identifies exactly what works now. Connected tools open the existing POS area; built-in tools open a purpose-made workspace.</p></div>{canCreate ? <Button asChild className="w-fit rounded-xl bg-white text-slate-950 hover:bg-slate-100"><Link href="/office/new"><FilePlus2 className="h-4 w-4" />New document</Link></Button> : null}</div>
    </section>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4" aria-label="Common tasks">{priorityActions.map((action) => { const Icon = OFFICE_SUITE_ICONS[action.icon]; return <Link key={action.label} href={action.href} className="group flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className={`rounded-xl p-3 text-white ${action.tone}`}><Icon className="h-5 w-5" /></div><div className="min-w-0"><p className="font-semibold text-slate-900">{action.label}</p><p className="text-xs text-slate-500">{action.detail}</p></div><ArrowRight className="ml-auto h-4 w-4 text-slate-300 transition group-hover:translate-x-1" /></Link>; })}</section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6" aria-label="Business overview">{[
      { label: "Documents", value: metrics.documents, href: "/office/documents" }, { label: "Customers", value: metrics.customers, href: "/customers" }, { label: "Team", value: metrics.employees, href: "/employees" }, { label: "Open orders", value: metrics.openOrders, href: "/orders" }, { label: "Office work", value: metrics.openWork, href: "/office/apps/projects" }, { label: "Expenses", value: metrics.pendingExpenses, href: "/finance/expenses" },
    ].map((item) => item.value == null ? null : <Link key={item.label} href={item.href} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 hover:bg-white hover:shadow-sm"><p className="text-2xl font-semibold tabular-nums text-slate-950">{item.value.toLocaleString()}</p><p className="mt-1 text-xs font-medium text-slate-600">{item.label}</p></Link>)}</section>
    <section>
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-500">Tool directory</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Find the exact tool you need</h2><p className="mt-1 text-sm text-slate-500">Search by action, then use the direct shortcut on the card.</p></div><div className="flex max-w-full gap-1 overflow-x-auto rounded-xl border bg-white p-1">{(["All", ...OFFICE_SUITE_GROUPS] as const).map((item) => <button key={item} onClick={() => setGroup(item)} className={cn("shrink-0 rounded-lg px-3 py-2 text-xs font-semibold", group === item ? "bg-slate-900 text-white" : "text-slate-500 hover:bg-slate-100")}>{item}</button>)}</div></div>
      <div className="relative mt-4"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try ‘book appointment’, ‘CSV’, ‘receipt’, or ‘QR code’" className="h-12 rounded-2xl bg-white pl-11 pr-11" />{query ? <button onClick={() => setQuery("")} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" aria-label="Clear search"><X className="h-4 w-4" /></button> : null}</div>
      <div className="mt-4 grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{visible.map((module, index) => { const Icon = OFFICE_SUITE_ICONS[module.icon]; const accent = OFFICE_ACCENTS[module.accent] ?? OFFICE_ACCENTS.slate; const isFavorite = favorites.includes(module.slug); return <article key={module.slug} className={cn("relative overflow-hidden rounded-2xl border border-slate-200 bg-white", index % 5 === 0 && "md:col-span-2 2xl:col-span-1")}><div className={cn("h-1.5", accent.icon)} /><div className="p-5"><div className="flex items-start gap-3"><div className={cn("rounded-xl p-2.5 text-white", accent.icon)}><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold text-slate-950">{module.name}</h3><Badge variant="outline" className={module.delivery === "built-in" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-blue-200 bg-blue-50 text-blue-700"}>{module.delivery === "built-in" ? "Built in" : "Connected"}</Badge></div><p className="mt-1 text-sm leading-5 text-slate-600">{module.description}</p></div><button onClick={() => favorite(module.slug)} className="rounded-lg p-2 text-slate-300 hover:bg-amber-50 hover:text-amber-500" aria-label={isFavorite ? `Remove ${module.name} from favorites` : `Favorite ${module.name}`}><Star className={cn("h-4 w-4", isFavorite && "fill-amber-400 text-amber-400")} /></button></div><div className="mt-4 flex flex-wrap gap-2">{module.features.map((feature) => <span key={feature} className="inline-flex items-center gap-1 rounded-lg bg-slate-50 px-2.5 py-1.5 text-xs text-slate-600"><CheckCircle2 className="h-3 w-3 text-emerald-500" />{feature}</span>)}</div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-4">{module.quickActions.map((action, actionIndex) => <Button key={action.label} asChild size="sm" variant={actionIndex === 0 ? "default" : "outline"} className="rounded-lg"><Link href={action.href ?? officeModuleHref(module)}>{action.label}{actionIndex === 0 ? <ArrowRight className="h-3.5 w-3.5" /> : null}</Link></Button>)}</div></div></article>; })}</div>
      {!visible.length ? <div className="mt-4 rounded-2xl border border-dashed p-10 text-center"><Search className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-semibold">No matching tool</p><p className="mt-1 text-sm text-slate-500">Try a simpler action or choose All.</p></div> : null}
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-slate-400" /><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Saved work</p><h2 className="text-lg font-semibold">Recent activity</h2></div></div>{recentRecords.length ? <div className="mt-4 grid gap-2 md:grid-cols-2">{recentRecords.slice(0, 6).map((record) => { const tool = OFFICE_SUITE_MODULES.find((item) => item.slug === record.workspace); if (!tool) return null; const Icon = OFFICE_SUITE_ICONS[tool.icon]; return <Link key={record.id} href={officeModuleHref(tool)} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 hover:bg-slate-100"><Icon className="h-4 w-4 text-slate-500" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{record.title}</p><p className="text-xs text-slate-500">{tool.name} · {record.createdBy.name}</p></div><span className="text-[11px] text-slate-400">{formatDistanceToNow(new Date(record.updatedAt), { addSuffix: true })}</span></Link>; })}</div> : <p className="mt-4 rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">Saved spreadsheets, decks, forms, projects, messages, and workflows will appear here.</p>}</section>
  </div>;
}
